## Importing variables

In [ ]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 3.0.6
NumPy: 2.5.3

In [1]:
import sys

print(sys.executable)

d:\Local Disk\CCT\Tseku\CA-ML\.venv\Scripts\python.exe

## Data Loading

Combining all 6 months of the raw .csv data that's avaible in a sinle .csv file

In [3]:
January = pd.read_csv("./Raw Dataset/202101-divvy-tripdata.csv")
February = pd.read_csv("./Raw Dataset/202102-divvy-tripdata.csv")
March = pd.read_csv("./Raw Dataset/202103-divvy-tripdata.csv")
April = pd.read_csv("./Raw Dataset/202104-divvy-tripdata.csv")  
May = pd.read_csv("./Raw Dataset/202105-divvy-tripdata.csv")    
June = pd.read_csv("./Raw Dataset/202106-divvy-tripdata.csv")   

## conbninng all the dataset avilble to one dastaet 
transport = pd.concat([January, February, March, April, May, June], ignore_index=True)

transport.info()

<class 'pandas.DataFrame'>
RangeIndex: 1973410 entries, 0 to 1973409
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             str
 1   rideable_type       str
 2   started_at          str
 3   ended_at            str
 4   start_station_name  str
 5   start_station_id    str
 6   end_station_name    str
 7   end_station_id      str
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       str
dtypes: float64(4), str(9)
memory usage: 195.7 MB

In [8]:
print("January:", len(January))
print("February:", len(February))
print("March:", len(March))
print("April:", len(April))
print("May:", len(May))
print("June:", len(June))
print("Combined:", len(transport))

January: 96834
February: 49622
March: 228496
April: 337230
May: 531633
June: 729595
Combined: 1973410

## Data Expolaration

In [9]:
transport.shape

transport.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E19E6F1B8D4C42ED,electric_bike,2021-01-23 16:14:19,2021-01-23 16:24:44,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.89,-87.72,member
1,DC88F20C2C55F27F,electric_bike,2021-01-27 18:43:08,2021-01-27 18:47:12,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.90,-87.69,member
2,EC45C94683FE3F27,electric_bike,2021-01-21 22:35:54,2021-01-21 22:37:14,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.90,-87.70,member
3,4FA453A75AE377DB,electric_bike,2021-01-07 13:31:13,2021-01-07 13:42:55,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.92,-87.69,member
4,BE5E8EB4E7263A0B,electric_bike,2021-01-23 02:24:02,2021-01-23 02:24:45,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.90,-87.70,casual

In [10]:
transport.isnull().sum()

ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    187412
start_station_id      187412
end_station_name      205117
end_station_id        205117
start_lat                  0
start_lng                  0
end_lat                 1920
end_lng                 1920
member_casual              0
dtype: int64

changing datatype of started_at , ended_at from object to datetime and removing column ride_id as it is useless

In [11]:
transport = transport.drop(columns=['ride_id'])
transport['started_at'] = pd.to_datetime(transport['started_at'])
transport['ended_at'] =  pd.to_datetime(transport['ended_at'])
transport.info()

<class 'pandas.DataFrame'>
RangeIndex: 1973410 entries, 0 to 1973409
Data columns (total 12 columns):
 #   Column              Dtype
---  ------              -----
 0   rideable_type       str
 1   started_at          datetime64[us]
 2   ended_at            datetime64[us]
 3   start_station_name  str
 4   start_station_id    str
 5   end_station_name    str
 6   end_station_id      str
 7   start_lat           float64
 8   start_lng           float64
 9   end_lat             float64
 10  end_lng             float64
 11  member_casual       str
dtypes: datetime64[us](2), float64(4), str(6)
memory usage: 180.7 MB

In [19]:
transport.head()

,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,ride_length_in_seconds,date,day_name,day,month,year
0,electric_bike,2021-01-23 16:14:19,2021-01-23 16:24:44,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.89,-87.72,member,0 days 00:10:25,625.0,2021-01-23,Saturday,23,1,2021
1,electric_bike,2021-01-27 18:43:08,2021-01-27 18:47:12,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.90,-87.69,member,0 days 00:04:04,244.0,2021-01-27,Wednesday,27,1,2021
2,electric_bike,2021-01-21 22:35:54,2021-01-21 22:37:14,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.90,-87.70,member,0 days 00:01:20,80.0,2021-01-21,Thursday,21,1,2021
3,electric_bike,2021-01-07 13:31:13,2021-01-07 13:42:55,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.92,-87.69,member,0 days 00:11:42,702.0,2021-01-07,Thursday,7,1,2021
4,electric_bike,2021-01-23 02:24:02,2021-01-23 02:24:45,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.90,-87.70,casual,0 days 00:00:43,43.0,2021-01-23,Saturday,23,1,2021

In [13]:
transport['ride_length'] = transport['ended_at'] - transport['started_at']
transport['ride_length_in_seconds'] = transport['ride_length'].dt.total_seconds()
transport['ride_length_in_seconds'].describe()

count    1.973410e+06
mean     1.487623e+03
std      1.344890e+04
min     -3.060000e+02
25%      4.340000e+02
50%      7.780000e+02
75%      1.427000e+03
max      3.356649e+06
Name: ride_length_in_seconds, dtype: float64

In [18]:
# transport.info()
transport['date'] = transport['started_at'].dt.date
transport['day_name'] = transport['started_at'].dt.day_name()
transport['day'] = transport['started_at'].dt.day
transport['month'] = transport['started_at'].dt.month
transport['year'] = transport['started_at'].dt.year
transport.info()

<class 'pandas.DataFrame'>
RangeIndex: 1973410 entries, 0 to 1973409
Data columns (total 19 columns):
 #   Column                  Dtype
---  ------                  -----
 0   rideable_type           str
 1   started_at              datetime64[us]
 2   ended_at                datetime64[us]
 3   start_station_name      str
 4   start_station_id        str
 5   end_station_name        str
 6   end_station_id          str
 7   start_lat               float64
 8   start_lng               float64
 9   end_lat                 float64
 10  end_lng                 float64
 11  member_casual           str
 12  ride_length             timedelta64[us]
 13  ride_length_in_seconds  float64
 14  date                    object
 15  day_name                str
 16  day                     int32
 17  month                   int32
 18  year                    int32
dtypes: datetime64[us](2), float64(5), int32(3), object(1), str(7), timedelta64[us](1)
memory usage: 263.5+ MB

In [15]:
###

In [16]:
transport.head()

,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,ride_length_in_seconds
0,electric_bike,2021-01-23 16:14:19,2021-01-23 16:24:44,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.89,-87.72,member,0 days 00:10:25,625.0
1,electric_bike,2021-01-27 18:43:08,2021-01-27 18:47:12,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.90,-87.69,member,0 days 00:04:04,244.0
2,electric_bike,2021-01-21 22:35:54,2021-01-21 22:37:14,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.90,-87.70,member,0 days 00:01:20,80.0
3,electric_bike,2021-01-07 13:31:13,2021-01-07 13:42:55,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.92,-87.69,member,0 days 00:11:42,702.0
4,electric_bike,2021-01-23 02:24:02,2021-01-23 02:24:45,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.90,-87.70,casual,0 days 00:00:43,43.0

### Using earth cordinates to calculate distance we already have longitude and latitude of both starting and ending point ( https://en.wikipedia.org/wiki/Haversine_formula ) using haverine formula

In [20]:
def haversine (lat1, lon1, lat2, lon2):
    earth_radius = 6371.0
    
    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)
    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)
    
    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    return earth_radius * c

transport['distance_km'] = haversine(
    transport['start_lat'],
    transport['start_lng'],
    transport['end_lat'],
    transport['end_lng'])

# transport['distance_m'] = transport['distance_km']*1000

transport.head()

,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,ride_length_in_seconds,date,day_name,day,month,year,distance_km
0,electric_bike,2021-01-23 16:14:19,2021-01-23 16:24:44,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.89,-87.72,member,0 days 00:10:25,625.0,2021-01-23,Saturday,23,1,2021,2.242244
1,electric_bike,2021-01-27 18:43:08,2021-01-27 18:47:12,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.90,-87.69,member,0 days 00:04:04,244.0,2021-01-27,Wednesday,27,1,2021,0.556327
2,electric_bike,2021-01-21 22:35:54,2021-01-21 22:37:14,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.90,-87.70,member,0 days 00:01:20,80.0,2021-01-21,Thursday,21,1,2021,0.280031
3,electric_bike,2021-01-07 13:31:13,2021-01-07 13:42:55,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.92,-87.69,member,0 days 00:11:42,702.0,2021-01-07,Thursday,7,1,2021,2.248210
4,electric_bike,2021-01-23 02:24:02,2021-01-23 02:24:45,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.90,-87.70,casual,0 days 00:00:43,43.0,2021-01-23,Saturday,23,1,2021,0.275752

In [21]:
transport['avg_speed_kmh'] = (transport['distance_km'] / (transport['ride_length_in_seconds'] / 3600))
transport.head()

,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,...,member_casual,ride_length,ride_length_in_seconds,date,day_name,day,month,year,distance_km,avg_speed_kmh
0,electric_bike,2021-01-23 16:14:19,2021-01-23 16:24:44,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.89,...,member,0 days 00:10:25,625.0,2021-01-23,Saturday,23,1,2021,2.242244,12.915324
1,electric_bike,2021-01-27 18:43:08,2021-01-27 18:47:12,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.90,...,member,0 days 00:04:04,244.0,2021-01-27,Wednesday,27,1,2021,0.556327,8.208101
2,electric_bike,2021-01-21 22:35:54,2021-01-21 22:37:14,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.90,...,member,0 days 00:01:20,80.0,2021-01-21,Thursday,21,1,2021,0.280031,12.601402
3,electric_bike,2021-01-07 13:31:13,2021-01-07 13:42:55,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.92,...,member,0 days 00:11:42,702.0,2021-01-07,Thursday,7,1,2021,2.248210,11.529283
4,electric_bike,2021-01-23 02:24:02,2021-01-23 02:24:45,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.90,...,casual,0 days 00:00:43,43.0,2021-01-23,Saturday,23,1,2021,0.275752,23.086200

In [22]:
transport['avg_speed_kmh'].describe(percentiles=[0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99])

d:\Local Disk\CCT\Tseku\CA-ML\.venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

count    1.971458e+06
mean              inf
std               NaN
min     -2.000403e+03
1%       0.000000e+00
5%       0.000000e+00
10%      4.841608e-01
25%      5.853441e+00
50%      9.668931e+00
75%      1.248300e+01
90%      1.499068e+01
95%      1.658128e+01
99%      2.000111e+01
max               inf
Name: avg_speed_kmh, dtype: float64

removing outliners as infinite speed is not possible and as 5th percentile shows 0km/hr it means thy have covered 0 distance.

In [35]:
transport_final = transport[(transport['avg_speed_kmh'] >= 3) & (transport['avg_speed_kmh'] <= 20)].copy()

In [31]:
transport_final.shape

(1624894, 21)

In [33]:
transport.shape

(1973410, 21)

In [34]:
transport_final['avg_speed_kmh'].describe(percentiles=[0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99])

count    1.624894e+06
mean     1.054398e+01
std      3.513491e+00
min      3.000004e+00
1%       3.336417e+00
5%       4.578368e+00
10%      5.807982e+00
25%      8.099521e+00
50%      1.051613e+01
75%      1.293516e+01
90%      1.518058e+01
95%      1.653090e+01
99%      1.870835e+01
max      1.999982e+01
Name: avg_speed_kmh, dtype: float64

In [40]:
transport_final.columns.tolist()

['rideable_type',
 'started_at',
 'ended_at',
 'start_station_name',
 'start_station_id',
 'end_station_name',
 'end_station_id',
 'start_lat',
 'start_lng',
 'end_lat',
 'end_lng',
 'member_casual',
 'ride_length',
 'ride_length_in_seconds',
 'date',
 'day_name',
 'day',
 'month',
 'year',
 'distance_km',
 'avg_speed_kmh']