**Programme Title:** HDIP Data Analytics

**Module Title(s):** Machine Learning for Business

**Assignment Title:** CA1

**Lecturer(s):** Dr. Muhammad Iqbal

**Student name:** Battsengel Gantsooj

**Student ID:** 2026124

**Submission date:** 30/10/2026

## Importing variables

In [1]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 2.3.3
NumPy: 2.3.5

In [2]:
import sys

print(sys.executable)

C:\Users\User\anaconda3\python.exe

## Data Loading

Combining all 6 months of the raw .csv data that's avaible in a sinle .csv file

In [3]:
January = pd.read_csv("./Raw Dataset/202101-divvy-tripdata.csv")
February = pd.read_csv("./Raw Dataset/202102-divvy-tripdata.csv")
March = pd.read_csv("./Raw Dataset/202103-divvy-tripdata.csv")
April = pd.read_csv("./Raw Dataset/202104-divvy-tripdata.csv")  
May = pd.read_csv("./Raw Dataset/202105-divvy-tripdata.csv")    
June = pd.read_csv("./Raw Dataset/202106-divvy-tripdata.csv")   

## conbininng all the dataset available to one dataset 
transport = pd.concat([January, February, March, April, May, June], ignore_index=True)

transport.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1973410 entries, 0 to 1973409
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 195.7+ MB

In [4]:
print("January:", len(January))
print("February:", len(February))
print("March:", len(March))
print("April:", len(April))
print("May:", len(May))
print("June:", len(June))
print("Combined:", len(transport))

January: 96834
February: 49622
March: 228496
April: 337230
May: 531633
June: 729595
Combined: 1973410

## Data Expolaration

In [5]:
transport.shape

transport.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E19E6F1B8D4C42ED,electric_bike,2021-01-23 16:14:19,2021-01-23 16:24:44,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.89,-87.72,member
1,DC88F20C2C55F27F,electric_bike,2021-01-27 18:43:08,2021-01-27 18:47:12,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.90,-87.69,member
2,EC45C94683FE3F27,electric_bike,2021-01-21 22:35:54,2021-01-21 22:37:14,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.90,-87.70,member
3,4FA453A75AE377DB,electric_bike,2021-01-07 13:31:13,2021-01-07 13:42:55,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.92,-87.69,member
4,BE5E8EB4E7263A0B,electric_bike,2021-01-23 02:24:02,2021-01-23 02:24:45,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.90,-87.70,casual

In [6]:
transport.isnull().sum()

ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    187412
start_station_id      187412
end_station_name      205117
end_station_id        205117
start_lat                  0
start_lng                  0
end_lat                 1920
end_lng                 1920
member_casual              0
dtype: int64

changing datatype of started_at , ended_at from object to datetime and removing column ride_id as it is useless

In [7]:
transport = transport.drop(columns=['ride_id'])
transport['started_at'] = pd.to_datetime(transport['started_at'])
transport['ended_at'] =  pd.to_datetime(transport['ended_at'])
transport.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1973410 entries, 0 to 1973409
Data columns (total 12 columns):
 #   Column              Dtype
---  ------              -----
 0   rideable_type       object
 1   started_at          datetime64[ns]
 2   ended_at            datetime64[ns]
 3   start_station_name  object
 4   start_station_id    object
 5   end_station_name    object
 6   end_station_id      object
 7   start_lat           float64
 8   start_lng           float64
 9   end_lat             float64
 10  end_lng             float64
 11  member_casual       object
dtypes: datetime64[ns](2), float64(4), object(6)
memory usage: 180.7+ MB

In [8]:
transport.head()

,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,electric_bike,2021-01-23 16:14:19,2021-01-23 16:24:44,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.89,-87.72,member
1,electric_bike,2021-01-27 18:43:08,2021-01-27 18:47:12,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.90,-87.69,member
2,electric_bike,2021-01-21 22:35:54,2021-01-21 22:37:14,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.90,-87.70,member
3,electric_bike,2021-01-07 13:31:13,2021-01-07 13:42:55,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.92,-87.69,member
4,electric_bike,2021-01-23 02:24:02,2021-01-23 02:24:45,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.90,-87.70,casual

In [9]:
transport['ride_length'] = transport['ended_at'] - transport['started_at']
transport['ride_length_in_seconds'] = transport['ride_length'].dt.total_seconds()
transport['ride_length_in_seconds'].describe()

count    1.973410e+06
mean     1.487623e+03
std      1.344890e+04
min     -3.060000e+02
25%      4.340000e+02
50%      7.780000e+02
75%      1.427000e+03
max      3.356649e+06
Name: ride_length_in_seconds, dtype: float64

In [10]:
# transport.info()
transport['date'] = transport['started_at'].dt.date
transport['day_name'] = transport['started_at'].dt.day_name()
transport['day'] = transport['started_at'].dt.day
transport['month'] = transport['started_at'].dt.month
transport['year'] = transport['started_at'].dt.year
transport.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1973410 entries, 0 to 1973409
Data columns (total 19 columns):
 #   Column                  Dtype
---  ------                  -----
 0   rideable_type           object
 1   started_at              datetime64[ns]
 2   ended_at                datetime64[ns]
 3   start_station_name      object
 4   start_station_id        object
 5   end_station_name        object
 6   end_station_id          object
 7   start_lat               float64
 8   start_lng               float64
 9   end_lat                 float64
 10  end_lng                 float64
 11  member_casual           object
 12  ride_length             timedelta64[ns]
 13  ride_length_in_seconds  float64
 14  date                    object
 15  day_name                object
 16  day                     int32
 17  month                   int32
 18  year                    int32
dtypes: datetime64[ns](2), float64(5), int32(3), object(8), timedelta64[ns](1)
memory usage: 263.5+ MB

In [11]:
###

In [12]:
transport.head()

,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,ride_length_in_seconds,date,day_name,day,month,year
0,electric_bike,2021-01-23 16:14:19,2021-01-23 16:24:44,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.89,-87.72,member,0 days 00:10:25,625.0,2021-01-23,Saturday,23,1,2021
1,electric_bike,2021-01-27 18:43:08,2021-01-27 18:47:12,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.90,-87.69,member,0 days 00:04:04,244.0,2021-01-27,Wednesday,27,1,2021
2,electric_bike,2021-01-21 22:35:54,2021-01-21 22:37:14,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.90,-87.70,member,0 days 00:01:20,80.0,2021-01-21,Thursday,21,1,2021
3,electric_bike,2021-01-07 13:31:13,2021-01-07 13:42:55,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.92,-87.69,member,0 days 00:11:42,702.0,2021-01-07,Thursday,7,1,2021
4,electric_bike,2021-01-23 02:24:02,2021-01-23 02:24:45,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.90,-87.70,casual,0 days 00:00:43,43.0,2021-01-23,Saturday,23,1,2021

### Using earth cordinates to calculate distance we already have longitude and latitude of both starting and ending point ( https://en.wikipedia.org/wiki/Haversine_formula ) using haverine formula

In [13]:
def haversine (lat1, lon1, lat2, lon2):
    earth_radius = 6371.0
    
    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)
    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)
    
    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    return earth_radius * c

transport['distance_km'] = haversine(
    transport['start_lat'],
    transport['start_lng'],
    transport['end_lat'],
    transport['end_lng'])

# transport['distance_m'] = transport['distance_km']*1000

transport.head()

,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,ride_length_in_seconds,date,day_name,day,month,year,distance_km
0,electric_bike,2021-01-23 16:14:19,2021-01-23 16:24:44,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.89,-87.72,member,0 days 00:10:25,625.0,2021-01-23,Saturday,23,1,2021,1.149830
1,electric_bike,2021-01-27 18:43:08,2021-01-27 18:47:12,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.90,-87.69,member,0 days 00:04:04,244.0,2021-01-27,Wednesday,27,1,2021,0.037009
2,electric_bike,2021-01-21 22:35:54,2021-01-21 22:37:14,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.90,-87.70,member,0 days 00:01:20,80.0,2021-01-21,Thursday,21,1,2021,0.034767
3,electric_bike,2021-01-07 13:31:13,2021-01-07 13:42:55,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.92,-87.69,member,0 days 00:11:42,702.0,2021-01-07,Thursday,7,1,2021,2.179569
4,electric_bike,2021-01-23 02:24:02,2021-01-23 02:24:45,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.90,-87.70,casual,0 days 00:00:43,43.0,2021-01-23,Saturday,23,1,2021,0.036287

In [14]:
transport['avg_speed_kmh'] = (transport['distance_km'] / (transport['ride_length_in_seconds'] / 3600))
transport.head()

,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,...,member_casual,ride_length,ride_length_in_seconds,date,day_name,day,month,year,distance_km,avg_speed_kmh
0,electric_bike,2021-01-23 16:14:19,2021-01-23 16:24:44,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.89,...,member,0 days 00:10:25,625.0,2021-01-23,Saturday,23,1,2021,1.149830,6.623019
1,electric_bike,2021-01-27 18:43:08,2021-01-27 18:47:12,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.90,...,member,0 days 00:04:04,244.0,2021-01-27,Wednesday,27,1,2021,0.037009,0.546040
2,electric_bike,2021-01-21 22:35:54,2021-01-21 22:37:14,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.90,...,member,0 days 00:01:20,80.0,2021-01-21,Thursday,21,1,2021,0.034767,1.564513
3,electric_bike,2021-01-07 13:31:13,2021-01-07 13:42:55,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.92,...,member,0 days 00:11:42,702.0,2021-01-07,Thursday,7,1,2021,2.179569,11.177276
4,electric_bike,2021-01-23 02:24:02,2021-01-23 02:24:45,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.90,...,casual,0 days 00:00:43,43.0,2021-01-23,Saturday,23,1,2021,0.036287,3.037949

In [15]:
transport['avg_speed_kmh'].describe(percentiles=[0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99])

count    1.971458e+06
mean              inf
std               NaN
min     -1.974422e+03
1%       0.000000e+00
5%       0.000000e+00
10%      4.180982e-02
25%      1.789523e+00
50%      6.020517e+00
75%      1.008123e+01
90%      1.317270e+01
95%      1.493234e+01
99%      1.845191e+01
max               inf
Name: avg_speed_kmh, dtype: float64

removing outliners as infinite speed is not possible and as 5th percentile shows 0km/hr it means thy have covered 0 distance.

In [16]:
transport_final = transport[(transport['avg_speed_kmh'] >= 3) & (transport['avg_speed_kmh'] <= 20)].copy()

In [17]:
transport_final.shape

(1330397, 21)

In [18]:
# checking something
transport.shape

(1973410, 21)

In [19]:
transport_final['avg_speed_kmh'].describe(percentiles=[0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99])

count    1.330397e+06
mean     8.880508e+00
std      3.706892e+00
min      3.000013e+00
1%       3.116195e+00
5%       3.576349e+00
10%      4.149770e+00
25%      5.838566e+00
50%      8.547593e+00
75%      1.147819e+01
90%      1.402340e+01
95%      1.552413e+01
99%      1.809084e+01
max      1.999983e+01
Name: avg_speed_kmh, dtype: float64

In [20]:
# to check list 
transport_final.columns.tolist()

['rideable_type',
 'started_at',
 'ended_at',
 'start_station_name',
 'start_station_id',
 'end_station_name',
 'end_station_id',
 'start_lat',
 'start_lng',
 'end_lat',
 'end_lng',
 'member_casual',
 'ride_length',
 'ride_length_in_seconds',
 'date',
 'day_name',
 'day',
 'month',
 'year',
 'distance_km',
 'avg_speed_kmh']

In [21]:
print("Dataset shape:", transport_final.shape)

print("\nData types:")
print(transport_final.dtypes)

Dataset shape: (1330397, 21)

Data types:
rideable_type                      object
started_at                 datetime64[ns]
ended_at                   datetime64[ns]
start_station_name                 object
start_station_id                   object
end_station_name                   object
end_station_id                     object
start_lat                         float64
start_lng                         float64
end_lat                           float64
end_lng                           float64
member_casual                      object
ride_length               timedelta64[ns]
ride_length_in_seconds            float64
date                               object
day_name                           object
day                                 int32
month                               int32
year                                int32
distance_km                       float64
avg_speed_kmh                     float64
dtype: object

In [22]:
print("\nMissing values:")
print(transport_final.isnull().sum())

print("\nDuplicate rows:", transport_final.duplicated().sum())

Missing values:
rideable_type                  0
started_at                     0
ended_at                       0
start_station_name        115224
start_station_id          115224
end_station_name          120569
end_station_id            120569
start_lat                      0
start_lng                      0
end_lat                        0
end_lng                        0
member_casual                  0
ride_length                    0
ride_length_in_seconds         0
date                           0
day_name                       0
day                            0
month                          0
year                           0
distance_km                    0
avg_speed_kmh                  0
dtype: int64

Duplicate rows: 120

### Dataset Cleaning finish

now checking data for for Exploratory Data Analysis (EDA)

## Exploratory Data Analysis (EDA)

In [23]:
# Visualise the result
import matplotlib.pyplot as plt

# Work with a copy so your cleaned dataset stays unchanged
df = transport_final.copy()

# Convert date to a proper datetime format
df["date"] = pd.to_datetime(df["date"], errors="coerce")

# Display plots inside the notebook
%matplotlib inline

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 1330397
Columns: 21

Checking Quality of the data¶

In [24]:
print("DATASET SHAPE")
print(df.shape)

print("\nMISSING VALUES")
print(df.isnull().sum().sort_values(ascending=False))

print("\nDUPLICATE ROWS")
print(df.duplicated().sum())

print("\nNUMERICAL SUMMARY")
print(df[[
    "ride_length_in_seconds",
    "distance_km",
    "avg_speed_kmh"
]].describe())

print("\nDATE RANGE")
print("Start:", df["started_at"].min())
print("End:", df["started_at"].max())

print("\nUSER TYPES")
print(df["member_casual"].value_counts(dropna=False))

print("\nBIKE TYPES")
print(df["rideable_type"].value_counts(dropna=False))

DATASET SHAPE
(1330397, 21)

MISSING VALUES
end_station_name          120569
end_station_id            120569
start_station_name        115224
start_station_id          115224
rideable_type                  0
ride_length_in_seconds         0
distance_km                    0
year                           0
month                          0
day                            0
day_name                       0
date                           0
end_lng                        0
ride_length                    0
member_casual                  0
started_at                     0
end_lat                        0
start_lng                      0
start_lat                      0
ended_at                       0
avg_speed_kmh                  0
dtype: int64

DUPLICATE ROWS
120

NUMERICAL SUMMARY
       ride_length_in_seconds   distance_km  avg_speed_kmh
count            1.330397e+06  1.330397e+06   1.330397e+06
mean             9.387874e+02  2.228858e+00   8.880508e+00
std              7.747345e+02  1.934514e+00   3.706892e+00
min              1.000000e+00  1.000754e-03   3.000013e+00
25%              4.390000e+02  9.451569e-01   5.838566e+00
50%              7.260000e+02  1.620361e+00   8.547593e+00
75%              1.200000e+03  2.877336e+00   1.147819e+01
max              1.972600e+04  3.092136e+01   1.999983e+01

DATE RANGE
Start: 2021-01-01 00:02:24
End: 2021-06-30 23:59:59

USER TYPES
member_casual
member    814085
casual    516312
Name: count, dtype: int64

BIKE TYPES
rideable_type
classic_bike     843130
electric_bike    432446
docked_bike       54821
Name: count, dtype: int64

Checking if there is any suspicious value

In [25]:
print("Zero or negative ride durations:",
      (df["ride_length_in_seconds"] <= 0).sum())

print("Negative distances:",
      (df["distance_km"] < 0).sum())

print("Infinite estimated speeds:",
      np.isinf(df["avg_speed_kmh"]).sum())

print("Missing estimated speeds:",
      df["avg_speed_kmh"].isna().sum())

print("Negative estimated speeds:",
      (df["avg_speed_kmh"] < 0).sum())

Zero or negative ride durations: 0
Negative distances: 0
Infinite estimated speeds: 0
Missing estimated speeds: 0
Negative estimated speeds: 0

Compare bike-type preferences

In [27]:
# Count trips by rider category and bike type
bike_counts = pd.crosstab(
    df["member_casual"],
    df["rideable_type"]
)

print("Trip counts:")
display(bike_counts)

# Calculate percentages within each rider category
bike_percentages = pd.crosstab(
    df["member_casual"],
    df["rideable_type"],
    normalize="index"
) * 100

print("Percentage of each rider category using each bike type:")
display(bike_percentages.round(2))

Trip counts:

rideable_type  classic_bike  docked_bike  electric_bike
member_casual
casual               269858        54820         191634
member               573272            1         240812

Percentage of each rider category using each bike type:

rideable_type  classic_bike  docked_bike  electric_bike
member_casual
casual                52.27        10.62          37.12
member                70.42         0.00          29.58